In [1]:
import os

In [2]:
%pwd

'c:\\Users\\Administrator\\Demand Forecasting 24122024\\End-to-End-Demand-Forecasting-for-Wooden-Pallets\\research'

In [3]:
os.chdir("../")

In [4]:
%pwd

'c:\\Users\\Administrator\\Demand Forecasting 24122024\\End-to-End-Demand-Forecasting-for-Wooden-Pallets'

In [5]:
import pandas as pd

In [6]:
df = pd.read_excel("artifacts/data_ingestion/DOC-20241224-WA0017..xlsx")
df.head()

c:\Users\Administrator\anaconda3\envs\MLProj\lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

,POSTING DATE,EFFECTIVE DATE,CREATE DATE,Customer/Vendor Code,Customer/Vendor Name,LOB,Region,BP TYPE,City,STATE,...,SO ID,SO Creation Date,SO Due Date,U_DocStatus,NumAtCard,U_SOTYPE,BP CATEGORY,Document Type,Vehicle Type,Direct Dispatch
0,2019-12-06,2019-12-06,2019-12-06,10002355,Cart Services Pvt. Ltd. _ Howrah _Uluberia ES...,FMCG,East,RENTAL,Howrah,West Bengal,...,2019/493,2019-12-05,2019-12-05,C,NaN,Rent,Ecommerce,Allot,19ft Vehicle,N
1,2019-12-06,2019-12-06,2019-12-06,10002355,Cart Services Pvt. Ltd. _ Howrah _Uluberia ES...,FMCG,East,RENTAL,Howrah,West Bengal,...,2019/493,2019-12-05,2019-12-05,C,NaN,Rent,Ecommerce,Allot,19ft Part Load,N
2,2019-12-20,2019-12-20,2019-12-20,10003155,Cart Services Pvt Ltd _ Gurgoan _Embassy Ind...,FMCG,North,RENTAL,Gurgaon,Haryana,...,2019/1133,2019-12-20,2019-12-27,C,NaN,Rent,Ecommerce,Allot,32ft SXL,N
3,2019-12-26,2019-12-26,2019-12-26,10001155,Cart Services Pvt. Ltd. _ Gurgoan _ Tauru,FMCG,North,RENTAL,Gurgaon,Haryana,...,2019/1309,2019-12-26,2020-01-02,C,NaN,Rent,Ecommerce,Allot,19ft Vehicle,N
4,2019-12-26,2019-12-26,2019-12-26,10001155,Cart Services Pvt. Ltd. _ Gurgoan _ Tauru,FMCG,North,RENTAL,Gurgaon,Haryana,...,2019/1309,2019-12-26,2020-01-02,C,NaN,Rent,Ecommerce,Allot,32ft SXL,N

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1582 entries, 0 to 1581
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   POSTING DATE          1582 non-null   datetime64[ns]
 1   EFFECTIVE DATE        1582 non-null   datetime64[ns]
 2   CREATE DATE           1582 non-null   datetime64[ns]
 3   Customer/Vendor Code  1582 non-null   int64
 4   Customer/Vendor Name  1582 non-null   object
 5   LOB                   1582 non-null   object
 6   Region                1582 non-null   object
 7   BP TYPE               1582 non-null   object
 8   City                  1582 non-null   object
 9   STATE                 1582 non-null   object
 10  From WhsCode          1582 non-null   object
 11  From WhsName          1582 non-null   object
 12  To whsCode            1582 non-null   int64
 13  TO WhsName            1582 non-null   object
 14  Model TYPE            1582 non-null   object
 15  Transfer Type         1582 non-null   object
 16  U_Frt                 1578 non-null   float64
 17  U_ActShipType         1582 non-null   object
 18  PRODUCT CATEGORY      1582 non-null   object
 19  ItemCode              1582 non-null   object
 20  QUANTITY              1582 non-null   int64
 21  UNIT                  1582 non-null   object
 22  RATE                  1582 non-null   int64
 23  SO ID                 1582 non-null   object
 24  SO Creation Date      1582 non-null   datetime64[ns]
 25  SO Due Date           1582 non-null   datetime64[ns]
 26  U_DocStatus           1582 non-null   object
 27  NumAtCard             0 non-null      float64
 28  U_SOTYPE              1582 non-null   object
 29  BP CATEGORY           1582 non-null   object
 30  Document Type         1582 non-null   object
 31  Vehicle Type          1582 non-null   object
 32  Direct Dispatch       1582 non-null   object
dtypes: datetime64[ns](5), float64(2), int64(4), object(22)
memory usage: 408.0+ KB

In [8]:
df.isnull().sum()

POSTING DATE               0
EFFECTIVE DATE             0
CREATE DATE                0
Customer/Vendor Code       0
Customer/Vendor Name       0
LOB                        0
Region                     0
BP TYPE                    0
City                       0
STATE                      0
From WhsCode               0
From WhsName               0
To whsCode                 0
TO WhsName                 0
Model TYPE                 0
Transfer Type              0
U_Frt                      4
U_ActShipType              0
PRODUCT CATEGORY           0
ItemCode                   0
QUANTITY                   0
UNIT                       0
RATE                       0
SO ID                      0
SO Creation Date           0
SO Due Date                0
U_DocStatus                0
NumAtCard               1582
U_SOTYPE                   0
BP CATEGORY                0
Document Type              0
Vehicle Type               0
Direct Dispatch            0
dtype: int64

In [ ]:
# Clean column names
df.columns = df.columns.str.strip().str.replace(' ', '_').str.lower()
df.head()

,posting_date,effective_date,create_date,customer/vendor_code,customer/vendor_name,lob,region,bp_type,city,state,from_whscode,from_whsname,to_whscode,to_whsname,model_type,transfer_type,u_frt,u_actshiptype,product_category,itemcode,quantity,unit,rate,so_id,so_creation_date,so_due_date,u_docstatus,numatcard,u_sotype,bp_category,document_type,vehicle_type,direct_dispatch
0,2019-12-06,2019-12-06,2019-12-06,10002355,Cart Services Pvt. Ltd. _ Howrah _Uluberia ES...,FMCG,East,RENTAL,Howrah,West Bengal,WB01,Pallet Company India Kolkata,10002355,"Cart Services Pvt. Ltd. - Howrah (Uluberia, ES...",Allot,Pallet CompanyOUT,8500.0,Pallet Company Transport borne by customer,Wooden Pallet,A010000023,200,Nos,1950,2019/493,2019-12-05,2019-12-05,C,NaN,Rent,Ecommerce,Allot,19ft Vehicle,N
1,2019-12-06,2019-12-06,2019-12-06,10002355,Cart Services Pvt. Ltd. _ Howrah _Uluberia ES...,FMCG,East,RENTAL,Howrah,West Bengal,WB01,Pallet Company India Kolkata,10002355,"Cart Services Pvt. Ltd. - Howrah (Uluberia, ES...",Allot,Pallet CompanyOUT,8500.0,Pallet Company Transport borne by customer,Wooden Pallet,A010000023,200,Nos,1950,2019/493,2019-12-05,2019-12-05,C,NaN,Rent,Ecommerce,Allot,19ft Part Load,N
2,2019-12-20,2019-12-20,2019-12-20,10003155,Cart Services Pvt Ltd _ Gurgoan _Embassy Ind...,FMCG,North,RENTAL,Gurgaon,Haryana,HY01,Pallet Company India Pataudi,10003155,Cart Services Pvt. Ltd. - Gurgoan (Embassy Ind...,Allot,Pallet CompanyOUT,4500.0,Pallet Company Transport borne by customer,Wooden Pallet,A010000054,200,Nos,2599,2019/1133,2019-12-20,2019-12-27,C,NaN,Rent,Ecommerce,Allot,32ft SXL,N
3,2019-12-26,2019-12-26,2019-12-26,10001155,Cart Services Pvt. Ltd. _ Gurgoan _ Tauru,FMCG,North,RENTAL,Gurgaon,Haryana,HY01,Pallet Company India Pataudi,10001155,Cart Services Pvt. Ltd. - Gurgoan ( Tauru),Allot,Pallet CompanyOUT,3500.0,Pallet Company Transport borne by customer,Wooden Pallet,A010000023,180,Nos,1950,2019/1309,2019-12-26,2020-01-02,C,NaN,Rent,Ecommerce,Allot,19ft Vehicle,N
4,2019-12-26,2019-12-26,2019-12-26,10001155,Cart Services Pvt. Ltd. _ Gurgoan _ Tauru,FMCG,North,RENTAL,Gurgaon,Haryana,HY01,Pallet Company India Pataudi,10001155,Cart Services Pvt. Ltd. - Gurgoan ( Tauru),Allot,Pallet CompanyOUT,4500.0,Pallet Company Transport borne by customer,Wooden Pallet,A010000023,326,Nos,1950,2019/1309,2019-12-26,2020-01-02,C,NaN,Rent,Ecommerce,Allot,32ft SXL,N

In [24]:
df = df.drop_duplicates()

In [30]:
# Drop 100% missing data for "numatcard" column
df = df.drop("numatcard", axis = 1)

Data Types - Convert columns to correct data type

In [32]:
df['posting_date'] = pd.to_datetime(df['posting_date'], errors='coerce')
df['effective_date'] = pd.to_datetime(df['effective_date'], errors='coerce')
df['create_date'] = pd.to_datetime(df['create_date'], errors='coerce')
df['so_creation_date'] = pd.to_datetime(df['so_creation_date'])
df['so_due_date'] = pd.to_datetime(df['so_due_date'])

In [33]:
df['quantity'] = df['quantity'].astype(int)
df['rate'] = df['rate'].astype(float)

In [34]:
# Convert to 'category' type for categorical columns
df['lob'] = df['lob'].astype('category')
df['region'] = df['region'].astype('category')
df['bp_type'] = df['bp_type'].astype('category')
df['product_category'] = df['product_category'].astype('category')
df['customer/vendor_code'] = df['customer/vendor_code'].astype(str)

In [35]:
# Cleaning city and state columns
df['city'] = df['city'].str.title()
city_std = {'Vijaywada': 'Vijayawada'}
state_std = {'Chattisgarh': 'Chhattisgarh'}

df['city'] = df['city'].replace(city_std)
df['state'] = df['state'].replace(state_std)

In [36]:
df.shape

(1376, 32)

In [37]:
df.columns

Index(['posting_date', 'effective_date', 'create_date', 'customer/vendor_code',
       'customer/vendor_name', 'lob', 'region', 'bp_type', 'city', 'state',
       'from_whscode', 'from_whsname', 'to_whscode', 'to_whsname',
       'model_type', 'transfer_type', 'u_frt', 'u_actshiptype',
       'product_category', 'itemcode', 'quantity', 'unit', 'rate', 'so_id',
       'so_creation_date', 'so_due_date', 'u_docstatus', 'u_sotype',
       'bp_category', 'document_type', 'vehicle_type', 'direct_dispatch'],
      dtype='object')

In [9]:
from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class DataValidationConfig:
    root_dir: Path
    STATUS_FILE: str
    unzip_data_dir: Path
    all_schema: dict

In [10]:
from DemandForecasting_WoodenPallets.constant import *
from DemandForecasting_WoodenPallets.utils.common import read_yaml, create_directories

In [11]:
class ConfigurationManager:
    def __init__(
        self,
        config_filepath = CONFIG_FILE_PATH,
        params_filepath = PARAMS_FILE_PATH,
        schema_filepath = SCHEMA_FILE_PATH):

        self.config = read_yaml(config_filepath)
        self.params = read_yaml(params_filepath)
        self.schema = read_yaml(schema_filepath)

        create_directories([self.config.artifacts_root])



    def get_data_validation_config(self) -> DataValidationConfig:
        config = self.config.data_validation
        schema = self.schema.COLUMNS

        create_directories([config.root_dir])

        data_validation_config = DataValidationConfig(
            root_dir=config.root_dir,
            STATUS_FILE=config.STATUS_FILE,
            unzip_data_dir=config.unzip_data_dir,
            all_schema=schema
        )

        return data_validation_config

In [12]:
import os
from DemandForecasting_WoodenPallets import logger

In [43]:
class DataValidation:
    def __init__(self, config: DataValidationConfig):
        self.config = config


    
    def validate_all_columns(self)-> bool:
        try:
            validation_status = None

            df = pd.read_excel(self.config.unzip_data_dir)
            all_cols = list(df.columns)

            all_schema = self.config.all_schema.keys()


            for col in all_cols:
                if col not in all_schema:
                    validation_status = False
                    with open(self.config.STATUS_FILE, 'w') as f:
                        f.write(f"Validation status: {validation_status}")
                else:
                    validation_status = True
                    with open(self.config.STATUS_FILE, 'w') as f:
                        f.write(f"Validation status: {validation_status}")

            return validation_status
        
        except Exception as e:
            raise e

In [14]:
try:
    config = ConfigurationManager()
    data_validation_config = config.get_data_validation_config()
    data_validation = DataValidation(config=data_validation_config)
    data_validation.validate_all_columns()
except Exception as e:
    raise e

[2025-03-27 13:35:13,920: INFO: common: yaml file: config\config.yaml loaded successfully]

[2025-03-27 13:35:13,932: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-27 13:35:13,944: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-27 13:35:13,946: INFO: common: created directory at: artifacts]
[2025-03-27 13:35:13,947: INFO: common: created directory at: artifacts/data_validation]

c:\Users\Administrator\anaconda3\envs\MLProj\lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

In [ ]:
import os
import pandas as pd
from DemandForecasting_WoodenPallets import logger
from DemandForecasting_WoodenPallets.entity.config_entity import DataValidationConfig

class DataValidation:
    def __init__(self, config: DataValidationConfig):
        self.config = config

    def validate_all_columns(self) -> bool:
        try:
            validation_status = None
            df = pd.read_excel(self.config.unzip_data_dir)
            all_cols = list(df.columns)
            all_schema = self.config.all_schema.keys()

            for col in all_cols:
                if col not in all_schema:
                    validation_status = False
                    with open(self.config.STATUS_FILE, 'w') as f:
                        f.write(f"Validation status: {validation_status}")
                    return validation_status  # Exit early if validation fails
                else:
                    validation_status = True

            # If all columns are valid, proceed to clean and validate data
            self.clean_and_validate_data(df)

            with open(self.config.STATUS_FILE, 'w') as f:
                f.write(f"Validation status: {validation_status}")

            return validation_status

        except Exception as e:
            raise e

    def clean_and_validate_data(self, df: pd.DataFrame) -> pd.DataFrame:
        # Clean column names
        df.columns = df.columns.str.strip().str.replace(' ', '_').str.lower()
        
        # Drop duplicates
        df = df.drop_duplicates()

        # Drop 100% missing data for "numatcard" column
        df = df.drop("numatcard", axis=1, errors='ignore')  # Use errors='ignore' to avoid KeyError

        # Convert columns to correct data type
        df['posting_date'] = pd.to_datetime(df['posting_date'], errors='coerce')
        df['effective_date'] = pd.to_datetime(df['effective_date'], errors='coerce')
        df['create_date'] = pd.to_datetime(df['create_date'], errors='coerce')
        df['so_creation_date'] = pd.to_datetime(df['so_creation_date'], errors='coerce')
        df['so_due_date'] = pd.to_datetime(df['so_due_date'], errors='coerce')

        df['quantity'] = df['quantity'].astype(int, errors='ignore')  # Use errors='ignore' to avoid ValueError
        df['rate'] = df['rate'].astype(float, errors='ignore')

        # For categorical columns, convert to 'category' type
        df['lob'] = df['lob'].astype('category', errors='ignore')
        df['region'] = df['region'].astype('category', errors='ignore')
        df['bp_type'] = df['bp_type'].astype('category', errors='ignore')
        df['product_category'] = df['product_category'].astype('category', errors='ignore')
        df['customer/vendor_code'] = df['customer/vendor_code'].astype(str)

        # Cleaning city and state columns
        df['city'] = df['city'].str.title()
        city_std = {'Vijaywada': 'Vijayawada'}
        state_std = {'Chattisgarh': 'Chhattisgarh'}

        df['city'] = df['city'].replace(city_std)
        df['state'] = df['state'].replace(state_std)

        # Extract features from the date columns
        df['posting_day_of_week'] = df['posting_date'].dt.day_name()
        df['posting_month'] = df['posting_date'].dt.month
        df['posting_year'] = df['posting_date'].dt.year
        df['so_creation_year'] = df['so_creation_date'].dt.year
        df['so_creation_month'] = df['so_creation_date'].dt.month
        df['so_due_year'] = df['so_due_date'].dt.year
        df['so_due_month'] = df['so_due_date'].dt.month

        # Calculate the lead time (processing time)
        df['effective_to_posting'] = (df['effective_date'] - df['posting_date']).dt.days
        df['lead_time'] = (df['so_due_date'] - df['so_creation_date']).dt.days

        df['posting_quarter'] = df['posting_date'].dt.quarter

        # Date falls on weekend
        df['is_posting_weekend'] = df['posting_date'].dt.dayofweek >= 5

        # Inventory activity at month-end
        df['is_posting_month_end'] = df['posting_date'].dt.is_month_end

    
        df = df.drop(columns=['posting_date', 'effective_date', 'create_date', 'so_creation_date', 'so_due_date'], errors='ignore')


        return df